# More information on the parameters can be found here: https://documentation.red-gate.com/flyway/flyway-cli-and-api/configuration/parameters

[environments.todoit]
url = "jdbc:postgresql://localhost:5432/todoit"
user = "bx_admin"
password = "nojXGZDdTeTuj3ZrcYYE"

[flyway]
environment="todoit"
locations = ["filesystem:migrations"]

# [environments.build]
# url = "jdbc:sqlite::memory:"
# user = "buildUser"
# password = "buildPassword"

# [flyway.check]
# buildEnvironment = "build"